In [ ]:
import os

In [ ]:
import numpy as np

In [ ]:
os.getcwd()

'/content/drive/MyDrive/STATSCDAC'

In [ ]:
os.chdir(r'/content/drive/MyDrive/STATSCDAC')
#changes the default saving folder of files to CDAC, this becomes the cwd
#create this folder and save all the files in this folder

In [ ]:
os.getcwd()

In [ ]:
x = np.array([3,5,4,5,7,6,8,9,7,2,1,4])

In [ ]:
arr2d = x.reshape(4,3)

In [ ]:
arr2d

array([[3, 5, 4],
       [5, 7, 6],
       [8, 9, 7],
       [2, 1, 4]])

In [ ]:
np.save('myarray',arr2d)
#np.save('name you want to give',array_name) to save in the cwd on desktop

np.save('name you want to give',array_name) to save in the cwd on desktop
it will be saved as myarray.npy in that folder

In [ ]:
newarray = np.load('myarray.npy')
#to import the myarray.npy from the folder

In [ ]:
arr2d

array([[3, 5, 4],
       [5, 7, 6],
       [8, 9, 7],
       [2, 1, 4]])

In [ ]:
newarray

array([[3, 5, 4],
       [5, 7, 6],
       [8, 9, 7],
       [2, 1, 4]])

**MATRIX MULTIPLICATION**
the no of col of first matrix must be equal to the rows of second matrix
the size of the resuit matrix will be no of rows of first one and the no of columns of 2nd one
2 commands can be used
1) arr1.dot(arr2)
2) np.matmul(arr1,arr2)

In [ ]:
x = np.array([[3,7,5],[1,2,3]])

In [ ]:
x

array([[3, 7, 5],
       [1, 2, 3]])

In [ ]:
y = np.array([[1,7],[2,4],[8,1]])

In [ ]:
y

array([[1, 7],
       [2, 4],
       [8, 1]])

In [ ]:
x.dot(y)

array([[57, 54],
       [29, 18]])

In [ ]:
np.matmul(x,y)

array([[57, 54],
       [29, 18]])

In [ ]:
from numpy import linalg

In [ ]:
from numpy.linalg import inv

solve the eqns
x+y+z=6,
2y+5z=-4,
2x+5y-z=27

A matrix = coefficients of x,y,z
B matrix = constants matrix
X= (A inverse) into B
X = gives the matrix containing x,y,z values

In [ ]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])

In [ ]:
B = np.array([6,-4,27])

In [ ]:
Ainv = np.linalg.inv(A)

In [ ]:
Ainv

array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

In [ ]:
B = B.reshape(3,1)

In [ ]:
B

array([[ 6],
       [-4],
       [27]])

In [ ]:
X = Ainv.dot(B)
#here we get X matrix which contains x, y,z values

In [ ]:
X

array([[ 5.],
       [ 3.],
       [-2.]])

**Generating some random numbers matrices in numpy**

In [ ]:
from numpy import random

In [ ]:
x = np.random.rand(10)
#generating 10 decimal values between 0 and 1

In [ ]:
x

array([0.74969753, 0.32550407, 0.66672086, 0.18606262, 0.5178844 ,
       0.48541264, 0.3731234 , 0.62181201, 0.93302751, 0.40663842])

In [ ]:
y = np.round(x,3)
#rounding of the number to three decimal places

In [ ]:
y

array([0.75 , 0.326, 0.667, 0.186, 0.518, 0.485, 0.373, 0.622, 0.933,
       0.407])

In [ ]:
np.random.randint(20,50)
#generating whole number between 20 and 50

24

In [ ]:
np.random.randint(20,50,5)
#generating 5 whole numbers between 20 and 50

array([38, 36, 31, 38, 20])

In [ ]:
x = np.random.rand(5)

In [ ]:
x

array([0.06205778, 0.61677476, 0.07804222, 0.6416321 , 0.2262793 ])

In [ ]:
y = np.round(x,3)

In [ ]:
y

array([0.062, 0.617, 0.078, 0.642, 0.226])

In [ ]:
z= np.random.randint(20,50,5)
#generating 5 whole numbers between 20 and 50

In [ ]:
z

array([39, 38, 32, 26, 28])

In [ ]:
a = z+y

In [ ]:
a

array([33.062, 48.617, 27.078, 20.642, 34.226])

**OPEN PY XL**

**openpyxl** is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.

In [ ]:
import openpyxl as op

Be careful using excel file. lookout for the headings in that file.
make sure we read from 2nd row.

we're creating Students.xlsx file and in that the worksheet name is Kharghar
Save this file in your cwd folder

Be careful about case sensitivity of filename and commands
---

Import the entire workbook

In [ ]:
wb = op.load_workbook('Students.xlsx')

In [ ]:
sht1 = wb['Kharghar']

In [ ]:
sht1['A3'].value

'Rakesh'

In [ ]:
x = sht1['A3'].value
#sht1['cellname'].value

In [ ]:
x

'Rakesh'

In [ ]:
sht1['B4'].value

'MLPython'

Inorder to run in loop:

use below command

In [ ]:
sht1.cell(3,1).value

'Rakesh'

To import the names from 2nd row to last into a list:

In [ ]:
sht1.max_row
#tells the maximum rows in the excel sheet

5

In [ ]:
sht1.max_column
#tells the maximum columns in the excel sheet

3

Reading of data should start from row 2 to row 5.

First create an empty list to store the result data

In [ ]:
students = []

In [ ]:
type(students)

list

In [ ]:
len(students)

0

In [ ]:
for ctr in range(2,6):
  x = sht1.cell(ctr,1).value
  students.append(x)

#ctr is the row number and 1 is the column
# to read the value from cell the command is sheet_name.cell(row_number,column_number).value
# we are giving row no starting as 2 because the heading is present in row 1

 to read the value from cell the command is:

  sheet_name.cell(row_number,column_number).value

In [ ]:
students

['Sudeep', 'Rakesh', 'Dhruv', 'Ruchika']

**Now getting the marks:**

In [ ]:
marks = []

In [ ]:
for ctr in range(2,6):
  x = sht1.cell(ctr,3).value
  marks.append(x)


#marks are in the 3rd column

In [ ]:
marks

[68, 84, 73, 82]

Another example:
we're writing the data from list to excel sheet now

In [ ]:
pl_name = ['Virat', 'Sachin', 'Dhoni','Rohit']

In [ ]:
pl_score = [34534,868964,46464,87564]

In [ ]:
wkbook = op.Workbook()

In [ ]:
sht1 = wkbook.create_sheet('IPL')

In [ ]:
sht1['A1'] = 'Name'

In [ ]:
sht1['B1'] = 'Score'

In [ ]:
wkbook.save('cricket.xlsx')

In [ ]:
len(pl_name)

4

In [ ]:
a = len(pl_name)

In [ ]:
a

4

In [ ]:
for ctr in range(2,a+2):
  x = pl_name[ctr-2]
  sht1.cell(ctr,1).value=x

#here ctr-2 because the ctr value is 2 at first and the virat index is at 0
#a+2 because a = 4 (length of pl_name) and the rows are 5 here including heading so we should give 6 in the range so a+2 in range
#be very careful while writing program.

In [ ]:
for ctr in range(2,a+2):
  x = pl_score[ctr-2]
  sht1.cell(ctr,2).value=x

In [ ]:
wkbook.save('cricket.xlsx')

#saving the workbook data in cricket.xlsx

**PANDAS**

In [ ]:
import pandas as pd

In [ ]:
x = [3,7,8,1,2]

In [ ]:
x[2]

8

In [ ]:
#Pandas series

ser1 = pd.Series(x)

In [ ]:
ser1

0    3
1    7
2    8
3    1
4    2
dtype: int64

In [ ]:
ser1[2]

8

In [ ]:
ser1= pd.Series(x, index = ['A','B','C','D','E'])

#giving custom indexes to the pandas series

In [ ]:
ser1

A    3
B    7
C    8
D    1
E    2
dtype: int64

In [ ]:
ser1[2]

#we can extract the elements using normal indexes or custom indexes. look at the below command

8

In [ ]:
ser1['C']

8

In [ ]:
x = {'Sudeep':'Blore','Sachin':'Mumbai','Virat':'Delhi','Ashwin':'Chennai'}

In [ ]:
ser2 = pd.Series(x)

#converting python dictionary into pandas series.

In [ ]:
ser2

Sudeep      Blore
Sachin     Mumbai
Virat       Delhi
Ashwin    Chennai
dtype: object

In [ ]:
ser2['Sudeep'] = 'Mumbai'

#changing the value of sudeep using index as Sudeep. we can change using normal number indexing also. See below command

In [ ]:
ser2

Sudeep     Mumbai
Sachin     Mumbai
Virat       Delhi
Ashwin    Chennai
dtype: object

In [ ]:
ser2[0] = 'Hyderabad'

In [ ]:
ser2

Sudeep    Hyderabad
Sachin       Mumbai
Virat         Delhi
Ashwin      Chennai
dtype: object

In [ ]:
new_pl = pd.Series(['Blore','Kolkata'], index = ['ABD','Sehwag'])

#creating another new series

In [ ]:
ser2 = ser2.append(new_pl)

#appening the new series to the previous one

<ipython-input-120-cffdc2c6b33d>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser2 = ser2.append(new_pl)

In [ ]:
ser2 = ser2.drop(['ABD'])

#deleting an element in pandas series

In [ ]:
ser2

Sudeep    Hyderabad
Sachin       Mumbai
Virat         Delhi
Ashwin      Chennai
Sehwag      Kolkata
dtype: object

DATAFRAME:

can be created using
1)manual creation process
2)Automatic creation process

1)manual creation process:

i)list option of creating df
if row wise data is given

ii) Dictonary option of creating df
if column wise data is given

In [ ]:
#lists of lists

stu_info = [['Sudeep','Blore',78],['Rakesh','Chennai',57],['Mayur','Mumbai',85],['Charu','Kharghar',80]]

#stu_info is a list in which each student info is a list and no of columns will be the no of elements in the sublist

In [ ]:
len(stu_info)

4

In [ ]:
#converting a list into DATAFRAME or creating a df from list

stu_df = pd.DataFrame(stu_info,columns=['Name','Location','Marks'])

In [ ]:
stu_df

     Name  Location  Marks
0  Sudeep     Blore     78
1  Rakesh   Chennai     57
2   Mayur    Mumbai     85
3   Charu  Kharghar     80

In [ ]:
#Creating a dictinary if data is given in column wise format.

pl_info = {'Name': ['Sachin','Virat','Rohit','Ashwin'], 'Score':[3463,64563,342,6467], 'Grade': ['A','B','A','C']}

In [ ]:
#creating a DF from Dictionary

pl_df = pd.DataFrame(pl_info)

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     A
3  Ashwin   6467     C

In [ ]:
#let's say ashwin is updraded from C to B
# changing the values in  a DF

pl_df.at[3,'Grade'] = 'B'

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     A
3  Ashwin   6467     B

In [ ]:
#updating or changing using DF.iat[row_number,column_number]
#DF.iat[row_number,column_number] = this can be used when the name is not known but indexes are known

pl_df.iat[3,2] = 'C'

#4th row,3rd column is ashwin

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     A
3  Ashwin   6467     C

In [ ]:
new_pl = pd.DataFrame([['Jadeja',34534,'B'],['Dhoni',5346,'A']], columns = ['Player','Runs','Grade'])

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     A
3  Ashwin   6467     C

In [ ]:
new_pl

   Player   Runs Grade
0  Jadeja  34534     B
1   Dhoni   5346     A

In [ ]:
pl_df = pl_df.append(new_pl)

<ipython-input-138-fab623f225dd>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pl_df = pl_df.append(new_pl)

In [ ]:
pl_df

     Name    Score Grade  Player     Runs
0  Sachin   3463.0     A     NaN      NaN
1   Virat  64563.0     B     NaN      NaN
2   Rohit    342.0     A     NaN      NaN
3  Ashwin   6467.0     C     NaN      NaN
0     NaN      NaN     B  Jadeja  34534.0
1     NaN      NaN     A   Dhoni   5346.0

To append new df to another df they should have same columns

In [ ]:
pl_df = pd.DataFrame([['Sachin',3463,'A'],['Virat',64563,'B'],['Rohit',342,'B'],['Ashwin',64676,'B']], colu

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     B
3  Ashwin  64676     B

In [ ]:
new_pl = pd.DataFrame([['Jadeja',34534,'B'],['Dhoni',5346,'A']], columns= ['Name','Score','Grade'])

In [ ]:
pl_df = pl_df.append(new_pl)

<ipython-input-157-fab623f225dd>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pl_df = pl_df.append(new_pl)

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     B
3  Ashwin  64676     B
0  Jadeja  34534     B
1   Dhoni   5346     A

In [ ]:
pl_df.shape

(6, 3)

In [ ]:
pl_df.shape[0]

6

In [ ]:
pl_df.index = range(pl_df.shape[0])

#reindexing the dataframe using range

In [ ]:
pl_df

     Name  Score Grade
0  Sachin   3463     A
1   Virat  64563     B
2   Rohit    342     B
3  Ashwin  64676     B
4  Jadeja  34534     B
5   Dhoni   5346     A

In [ ]:
y = ['MI','RCB','MI','RR','CSK','CSK']

#Creating new list to add to the data frame.
#be careful about the no of rows. they should be in same number in both list and DF

In [ ]:
len(y)

6

In [ ]:
pl_df['Team'] = y

#For adding new rows (which is another df) in an exiting dataframe - use DataFrame.Append(new df_name) function
# For adding new columns in an exiting dataframe - use the above command

#adding the new column by giving the column name as 'Team' using list 'y'

In [ ]:
pl_df

     Name  Score Grade Team
0  Sachin   3463     A   MI
1   Virat  64563     B  RCB
2   Rohit    342     B   MI
3  Ashwin  64676     B   RR
4  Jadeja  34534     B  CSK
5   Dhoni   5346     A  CSK